apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: frontend_mapping
      prefix: /
      service: frontend:80
spec:
  ports:
  - name: frontend
    port: 80
    targetPort: 8080
  selector:
    app: frontend