apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: "frontend-microservice"
        image: gcr.io/magasinudes-241416/frontend:latest
        ports:
        - name: http
          containerPort: 5000
