apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: frontend_mapping
      prefix: /
      service: frontend:5000
spec:
  ports:
  - name: frontend
    port: 5000
    targetPort: 5000
  selector:
    app: frontend