apiVersion: "v1"
kind: "Service"
metadata:
  name: "authentication-service"
  namespace: "default"
  labels:
    app: authentication
spec:
  ports:
  - protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    app: "authentication"
  type: "LoadBalancer"
  loadBalancerIP: ""