apiVersion: v1
kind: Service
metadata:
  name: authentication
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: authentication_mapping
      prefix: /cas/
      service: authentication:8080
spec:
  ports:
  - name: authentication
    port: 8080
    targetPort: 8080
  selector:
    app: authentication