apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources
  labels:
    app: resources
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resources
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: resources
    spec:
      containers:
      - name: "resources-microservice"
        image: gcr.io/magasinudes-241416/resources-microservice
        ports:
        - name: http
          containerPort: 8080
