apiVersion: v1
kind: Service
metadata:
  name: resources-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: resources_mapping
      prefix: /resources/
      service: resources:8080
spec:
  ports:
  - name: resources
    port: 80
    targetPort: 8080
  selector:
    app: resources