apiVersion: v1
kind: Service
metadata:
  name: ressources
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: ressources_mapping
      prefix: /ressources/
      service: ressources:8080
spec:
  ports:
  - name: ressources
    port: 8080
    targetPort: 8080
  selector:
    app: ressources